name: Run the testsuite

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2.2.0
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}

    - name: Version information
      run: |
        java -version
        mvn --version
    - name: Run tests and package
      run: mvn -D"http.keepAlive=false" -D"maven.wagon.http.pool=false" -D"maven.wagon.httpconnectionManager.ttlSeconds=120" -B -V clean package
